const ORDER_STATUS = {
  ORDER_PLACED: "ORDER_PLACED",

  DESIGN_APPROVED: "DESIGN_APPROVED",
  DESIGN_REJECTED: "DESIGN_REJECTED",

  ADVANCE_PAYMENT_PENDING: "ADVANCE_PAYMENT_PENDING",
  ADVANCE_PAYMENT_COMPLETED: "ADVANCE_PAYMENT_COMPLETED",

  PRINTING_IN_PROGRESS: "PRINTING_IN_PROGRESS",
  PRINTING_COMPLETED: "PRINTING_COMPLETED",

  REMAINING_PAYMENT_PENDING: "REMAINING_PAYMENT_PENDING",
  REMAINING_PAYMENT_COMPLETED: "REMAINING_PAYMENT_COMPLETED",

  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",

  ORDER_COMPLETED: "ORDER_COMPLETED"
};

module.exports = { ORDER_STATUS };
